In [1]:
import pandas as pd
import os
from pathlib import Path

os.chdir('..')
parent_dir = Path.cwd()

pd.options.display.float_format = '{:1.2f}'.format
pd.options.display.max_columns = None
pd.options.display.max_rows = None

In [2]:
url = "https://fred.stlouisfed.org/graph/fredgraph.csv?id=MORTGAGE30US"
mortgage = pd.read_csv(url, parse_dates=['observation_date'])
mortgage = mortgage[mortgage['observation_date'] >= '2024-01-01'].reset_index().drop(columns=['index'])
mortgage.columns = ['date', 'rate_30yr_fixed']

In [3]:
mortgage.head()

        date  rate_30yr_fixed
0 2024-01-04             6.62
1 2024-01-11             6.66
2 2024-01-18             6.60
3 2024-01-25             6.69
4 2024-02-01             6.63

In [4]:
mortgage['year_month'] = mortgage['date'].dt.to_period('M')
mortgage_monthly = (
 mortgage.groupby('year_month')['rate_30yr_fixed']
 .mean()
 .reset_index()
)
mortgage_monthly.head()

  year_month  rate_30yr_fixed
0    2024-01             6.64
1    2024-02             6.78
2    2024-03             6.82
3    2024-04             6.99
4    2024-05             7.06

In [5]:
sold = pd.read_csv(str(parent_dir)+'/week 1/sold_merged_residential.csv', encoding='latin-1')
sold['year_month'] = pd.to_datetime(sold['CloseDate']).dt.to_period('M')
sold[['CloseDate', 'year_month']].head()

C:\Users\Jamesb\AppData\Local\Temp\ipykernel_23544\3543926219.py:1: DtypeWarning: Columns (0,1,9,64,78,79,80,82,83) have mixed types. Specify dtype option on import or set low_memory=False.
  sold = pd.read_csv(str(parent_dir)+'/week 1/sold_merged_residential.csv', encoding='latin-1')

    CloseDate year_month
0  2024-01-26    2024-01
1  2024-01-05    2024-01
2  2024-01-05    2024-01
3  2024-01-30    2024-01
4  2024-01-29    2024-01

In [6]:
listings = pd.read_csv(str(parent_dir)+'/week 1/listing_merged_residential.csv', encoding='latin-1')
listings['year_month'] = pd.to_datetime(
    listings['ListingContractDate']
).dt.to_period('M')
listings[[ 'ListingContractDate','year_month']].head()

C:\Users\Jamesb\AppData\Local\Temp\ipykernel_23544\1923958767.py:1: DtypeWarning: Columns (2,43) have mixed types. Specify dtype option on import or set low_memory=False.
  listings = pd.read_csv(str(parent_dir)+'/week 1/listing_merged_residential.csv', encoding='latin-1')

  ListingContractDate year_month
0          2024-01-01    2024-01
1          2024-01-24    2024-01
2          2024-01-12    2024-01
3          2024-01-20    2024-01
4          2024-01-12    2024-01

In [7]:
sold_with_rates = sold.merge(mortgage_monthly, on='year_month', how='left')
listings_with_rates = listings.merge(mortgage_monthly, on='year_month', how='left')

In [8]:
print(sold_with_rates['rate_30yr_fixed'].isnull().sum())
print(listings_with_rates['rate_30yr_fixed'].isnull().sum())

0
0

In [9]:
sold_with_rates[
    ['CloseDate', 'year_month', 'ClosePrice', 'rate_30yr_fixed']
].head()

    CloseDate year_month  ClosePrice  rate_30yr_fixed
0  2024-01-26    2024-01   240000.00             6.64
1  2024-01-05    2024-01   815000.00             6.64
2  2024-01-05    2024-01   810000.00             6.64
3  2024-01-30    2024-01   858000.00             6.64
4  2024-01-29    2024-01  1890500.00             6.64

In [10]:
sold_with_rates[
    ['CloseDate', 'year_month', 'ClosePrice', 'rate_30yr_fixed']
].drop_duplicates('year_month').head(100)

         CloseDate year_month  ClosePrice  rate_30yr_fixed
0       2024-01-26    2024-01   240000.00             6.64
11203   2024-02-07    2024-02  1249000.00             6.78
24266   2024-03-06    2024-03  1290000.00             6.82
40050   2024-04-02    2024-04   250000.00             6.99
57345   2024-05-31    2024-05  3300000.00             7.06
75819   2024-06-28    2024-06  4250000.00             6.92
92444   2024-07-31    2024-07   929000.00             6.85
110253  2024-08-09    2024-08   210000.00             6.50
127044  2024-09-12    2024-09  1090000.00             6.18
141599  2024-10-04    2024-10   208000.00             6.43
157874  2024-11-27    2024-11  1085000.00             6.80
172032  2024-12-09    2024-12  1120000.00             6.71
186252  2025-01-31    2025-01   350000.00             6.96
197228  2025-02-11    2025-02   875000.00             6.84
209329  2025-03-26    2025-03   640000.00             6.65
223738  2025-04-30    2025-04  2700000.00             6.72
239589  2025-05-08    2025-05   399500.00             6.82
255133  2025-06-13    2025-06   890000.00             6.82
270462  2025-07-31    2025-07  1040000.00             6.72
286262  2025-08-11    2025-08  2800000.00             6.59
301487  2025-09-30    2025-09  3775000.00             6.35
316621  2025-10-31    2025-10   960000.00             6.25
332518  2025-11-30    2025-11  1250000.00             6.24
345496  2025-12-31    2025-12  1998000.00             6.19
359471  2026-01-02    2026-01 11706000.00             6.10
369554  2026-02-27    2026-02  2299000.00             6.05
381852  2026-03-27    2026-03  4687000.00             6.18

In [12]:
listings_with_rates[
    ['ListingContractDate', 'year_month', 'ListPrice', 'rate_30yr_fixed']
].drop_duplicates('year_month').head(100)

       ListingContractDate year_month  ListPrice  rate_30yr_fixed
0               2024-01-01    2024-01 1340000.00             6.64
17007           2024-02-18    2024-02  799999.00             6.78
34497           2024-03-27    2024-03 3550000.00             6.82
54998           2024-04-24    2024-04  549000.00             6.99
79023           2024-05-10    2024-05  929000.00             7.06
104470          2024-06-11    2024-06  699000.00             6.92
127780          2024-07-31    2024-07  949000.00             6.85
150799          2024-08-18    2024-08  300000.00             6.50
173014          2024-09-17    2024-09  570000.00             6.18
195271          2024-10-22    2024-10  788000.00             6.43
217192          2024-11-11    2024-11 1399990.00             6.80
232300          2024-12-30    2024-12  373900.00             6.71
242994          2025-01-24    2025-01  879900.00             6.96
265684          2025-02-25    2025-02  595500.00             6.84
287614          2025-03-31    2025-03 5295000.00             6.65
312718          2025-04-12    2025-04  499000.00             6.72
339413          2025-05-31    2025-05  575000.00             6.82
365851          2025-06-06    2025-06  659000.00             6.82
382907          2025-07-13    2025-07  199900.00             6.72
400101          2025-08-08    2025-08  700000.00             6.59
415759          2025-09-23    2025-09  980000.00             6.35
432618          2025-10-21    2025-10 2598000.00             6.25
449804          2025-11-01    2025-11 5990000.00             6.24
461998          2025-12-18    2025-12  700000.00             6.19
472514          2026-01-15    2026-01  850000.00             6.10
494622          2026-02-13    2026-02 1989000.00             6.05
514619          2026-03-31    2026-03  385999.00             6.18

In [ ]:
# listings_with_rates.to_csv(str(parent_dir)+'/week 2-3/FRED_rates_listings.csv', index=False)
# sold_with_rates.to_csv(str(parent_dir)+'/week 2-3/FRED_rates_sold.csv', index=False)